version: '3.8'

services:
  app:
    build:
      context: .
      target: base
      args:
        NODE_ENV: development
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - ${PWD-.}:/usr/app